type PdfIssue = {
  severity: string;
  category: string;
  title: string;
  recommendation: string;
  affectedUrl?: string | null;
};

type PdfInput = {
  domain: string;
  url: string;
  overallScore: number | null;
  pagesCrawled: number;
  issuesCount: number;
  criticalCount: number;
  highCount: number;
  completedAt: Date | null;
  scoringVersion: string;
  scores: Record<string, number | null>;
  issues: PdfIssue[];
};

function escapePdfText(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildPageContent(lines: string[], pageHeight = 792, margin = 50) {
  const content: string[] = ["BT", "/F1 11 Tf", "14 TL", `${margin} ${pageHeight - margin} Td`];
  let first = true;
  for (const line of lines) {
    const safe = escapePdfText(line.slice(0, 110));
    if (!first) content.push("T*");
    content.push(`(${safe}) Tj`);
    first = false;
  }
  content.push("ET");
  return content.join("\n");
}

export function buildAuditPdf(input: PdfInput): Buffer {
  const header = [
    "HUKAN SEO AUDITOR",
    "Professional SEO Audit Report",
    "",
    `Website: ${input.domain}`,
    `URL: ${input.url}`,
    `Completed: ${input.completedAt ? input.completedAt.toISOString() : "n/a"}`,
    `Scoring version: ${input.scoringVersion}`,
    "",
    `Overall score: ${input.overallScore ?? "n/a"} / 100`,
    `Pages crawled: ${input.pagesCrawled}`,
    `Issues: ${input.issuesCount} (critical ${input.criticalCount}, high ${input.highCount})`,
    "",
    "CATEGORY SCORES",
    "---------------",
  ];

  for (const [label, value] of Object.entries(input.scores)) {
    header.push(`${label}: ${value ?? "n/a"}`);
  }

  header.push("", "ISSUES (top 40)", "---------------", "");

  const issueLines: string[] = [];
  for (const issue of input.issues.slice(0, 40)) {
    issueLines.push(`[${issue.severity}] ${issue.title}`);
    issueLines.push(`  Category: ${issue.category}`);
    if (issue.affectedUrl) issueLines.push(`  URL: ${issue.affectedUrl}`);
    issueLines.push(`  Fix: ${issue.recommendation}`);
    issueLines.push("");
  }
  if (issueLines.length === 0) issueLines.push("No issues recorded.");

  const allLines = [
    ...header,
    ...issueLines,
    "",
    "Generated by Hukan SEO Auditor",
    "KES 500 one-time audit product",
  ];

  const perPage = 45;
  const pages: string[][] = [];
  for (let i = 0; i < allLines.length; i += perPage) {
    pages.push(allLines.slice(i, i + perPage));
  }
  if (pages.length === 0) pages.push(["Empty report"]);

  const objects: string[] = [];
  objects.push("1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n");
  const kids = pages.map((_, i) => `${3 + i * 2} 0 R`).join(" ");
  objects.push(`2 0 obj<< /Type /Pages /Kids [${kids}] /Count ${pages.length} >>endobj\n`);

  let objNum = 3;
  for (let i = 0; i < pages.length; i++) {
    const contentObj = objNum + 1;
    objects.push(
      `${objNum} 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${contentObj} 0 R /Resources << /Font << /F1 ${3 + pages.length * 2} 0 R >> >> >>endobj\n`
    );
    const stream = buildPageContent(pages[i]);
    objects.push(`${contentObj} 0 obj<< /Length ${stream.length} >>stream\n${stream}\nendstream\nendobj\n`);
    objNum += 2;
  }

  const fontObj = objNum;
  objects.push(`${fontObj} 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n`);

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj;
  }
  const xrefPos = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < offsets.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefPos}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
